DEJT:
  CADERNOS:
    TST-00 : "corpo:formulario:plcLogicaItens:0:j_id131"
    TRT-01 : "corpo:formulario:plcLogicaItens:1:j_id131"
    TRT-02 : "corpo:formulario:plcLogicaItens:2:j_id131"
    TRT-03 : "corpo:formulario:plcLogicaItens:3:j_id131"
    TRT-04 : "corpo:formulario:plcLogicaItens:4:j_id131"
    TRT-05 : "corpo:formulario:plcLogicaItens:5:j_id131"
    TRT-06 : "corpo:formulario:plcLogicaItens:6:j_id131"
    TRT-07 : "corpo:formulario:plcLogicaItens:7:j_id131"
    TRT-08 : "corpo:formulario:plcLogicaItens:8:j_id131"
    TRT-09 : "corpo:formulario:plcLogicaItens:9:j_id131"
    TRT-10 : "corpo:formulario:plcLogicaItens:10:j_id131"
    TRT-11 : "corpo:formulario:plcLogicaItens:11:j_id131"
    TRT-12 : "corpo:formulario:plcLogicaItens:12:j_id131"
    TRT-13 : "corpo:formulario:plcLogicaItens:13:j_id131"
    TRT-14 : "corpo:formulario:plcLogicaItens:14:j_id131"
    TRT-15 : "corpo:formulario:plcLogicaItens:15:j_id131"
    TRT-16 : "corpo:formulario:plcLogicaItens:16:j_id131"
    TRT-17 : "corpo:formulario:plcLogicaItens:17:j_id131"
    TRT-18 : "corpo:formulario:plcLogicaItens:18:j_id131"
    TRT-19 : "corpo:formulario:plcLogicaItens:19:j_id131"
    TRT-20 : "corpo:formulario:plcLogicaItens:20:j_id131"
    TRT-21 : "corpo:formulario:plcLogicaItens:21:j_id131"
    TRT-22 : "corpo:formulario:plcLogicaItens:22:j_id131"
    TRT-23 : "corpo:formulario:plcLogicaItens:23:j_id131"
    TRT-24 : "corpo:formulario:plcLogicaItens:24:j_id131"
  HEADERS:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
  API_ENDPOINT: "https://dejt.jt.jus.br/dejt/f/n/diariocon"